# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test suite

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    # needs: [lintcode,lintstyle,lintdocs] # we could add prior jobs for linting, if desired
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '3.3.1'

      - name: cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
        - run: cd test-proxy && meteor npm run test
